// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGprMLp0Ul-_MKVt8qazwVnpxxGpWJjXg',
    appId: '1:282765183722:web:881899e512b28d54cbe593',
    messagingSenderId: '282765183722',
    projectId: 'nelta-app-ym',
    authDomain: 'nelta-app-ym.firebaseapp.com',
    storageBucket: 'nelta-app-ym.appspot.com',
    measurementId: 'G-8VXTS7HB1V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1wEu-YIYTSiiqD2hmZmbmWJolKtnv0Hs',
    appId: '1:282765183722:android:743d7e84c44b9b02cbe593',
    messagingSenderId: '282765183722',
    projectId: 'nelta-app-ym',
    storageBucket: 'nelta-app-ym.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHxyFc4j-X8OGg7H1Tf_f_9panAHYtxTw',
    appId: '1:282765183722:ios:57efec45287bc864cbe593',
    messagingSenderId: '282765183722',
    projectId: 'nelta-app-ym',
    storageBucket: 'nelta-app-ym.appspot.com',
    iosClientId: '282765183722-siognji97qhrihkdmnbfi7v5pmkm5lrj.apps.googleusercontent.com',
    iosBundleId: 'org.np.nelta',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHxyFc4j-X8OGg7H1Tf_f_9panAHYtxTw',
    appId: '1:282765183722:ios:57efec45287bc864cbe593',
    messagingSenderId: '282765183722',
    projectId: 'nelta-app-ym',
    storageBucket: 'nelta-app-ym.appspot.com',
    iosClientId: '282765183722-siognji97qhrihkdmnbfi7v5pmkm5lrj.apps.googleusercontent.com',
    iosBundleId: 'org.np.nelta',
  );
}
